# fly.toml app configuration file generated for htmx-todo on 2023-10-07T14:47:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "htmx-todo"
primary_region = "nrt"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
